#pragma once

enum MapEditorState {
    MAP_EDITOR_STATE_IDLE,
    MAP_EDITOR_STATE_TILE,
    MAP_EDITOR_STATE_ERASING,
    MAP_EDITOR_STATE_DRAWING,
    MAP_EDITOR_STATE_BACKGROUND,
    MAP_EDITOR_STATE_BACKGROUND_COLOR,
    MAP_EDITOR_STATE_ITEM,
    MAP_EDITOR_STATE_BADDIE,
    MAP_EDITOR_STATE_BLOCK,
};